CREATE TABLE POSTS(
    ID NUMBER,
    CONSTRAINT POST_PK PRIMARY KEY (ID),
    NAME NVARCHAR2(30),
    DESCRIPTION NVARCHAR2(200),
    PRICE NUMBER,
    CURRENCY NVARCHAR2(3),
    CATEGORY NVARCHAR2(30),
    SUBCATEGORY NVARCHAR2(30),
    CITY NVARCHAR2(20),
    PHONE NVARCHAR2(15),
    DATE_FROM DATE,
    DATE_TO DATE,
    DATE_CREATED DATE,
    USER_ID NUMBER,
    CONSTRAINT USER_FK FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);