CREATE TABLE FLIGHTS(
    ID NUMBER,
    CONSTRAINT FLIGHTS_PK PRIMARY KEY (ID),
    PLANE_ID NUMBER,
    CONSTRAINT PLANE_FK FOREIGN KEY (PLANE_ID) REFERENCES PLANES(ID),
    DATE_FLIGHT DATE,
    CITY_FROM NVARCHAR2(20),
    CITY_TO NVARCHAR2(20)
);