CREATE TABLE FILES(
    ID NUMBER,
    CONSTRAINT FILES_PK PRIMARY KEY(ID),
    NAME_F NVARCHAR2(20),
    FORMAT_F NVARCHAR2(10),
    SIZE_F NUMBER,
    STORAGE_ID NUMBER,
    CONSTRAINT STORAGE_FK FOREIGN KEY (STORAGE_ID) REFERENCES STORAGES(ID)
);